import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'
import Header from '../components/Headers'
import Layout from '../components/Layout'
import SideDrawer from '../components/SideDrawer'
import Hero from '../section/Hero'
import Link from 'next/link'

const Home: NextPage = () => {

  
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/job-portal.png" />
      </Head>
        <Hero />       
        <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Maiores, recusandae. Ab consequatur, excepturi tempore non cupiditate laudantium impedit vero explicabo sunt atque pariatur. Ducimus quasi corrupti repudiandae aut, error accusantium necessitatibus culpa molestias in vero nostrum tempora inventore, odio, recusandae dolore! Tenetur dicta corrupti placeat voluptates modi delectus rem quo?</p>
        <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Maiores, recusandae. Ab consequatur, excepturi tempore non cupiditate laudantium impedit vero explicabo sunt atque pariatur. Ducimus quasi corrupti repudiandae aut, error accusantium necessitatibus culpa molestias in vero nostrum tempora inventore, odio, recusandae dolore! Tenetur dicta corrupti placeat voluptates modi delectus rem quo?</p>
        <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Maiores, recusandae. Ab consequatur, excepturi tempore non cupiditate laudantium impedit vero explicabo sunt atque pariatur. Ducimus quasi corrupti repudiandae aut, error accusantium necessitatibus culpa molestias in vero nostrum tempora inventore, odio, recusandae dolore! Tenetur dicta corrupti placeat voluptates modi delectus rem quo?</p>
        <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Maiores, recusandae. Ab consequatur, excepturi tempore non cupiditate laudantium impedit vero explicabo sunt atque pariatur. Ducimus quasi corrupti repudiandae aut, error accusantium necessitatibus culpa molestias in vero nostrum tempora inventore, odio, recusandae dolore! Tenetur dicta corrupti placeat voluptates modi delectus rem quo?</p>
        <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Maiores, recusandae. Ab consequatur, excepturi tempore non cupiditate laudantium impedit vero explicabo sunt atque pariatur. Ducimus quasi corrupti repudiandae aut, error accusantium necessitatibus culpa molestias in vero nostrum tempora inventore, odio, recusandae dolore! Tenetur dicta corrupti placeat voluptates modi delectus rem quo?</p>
        <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Maiores, recusandae. Ab consequatur, excepturi tempore non cupiditate laudantium impedit vero explicabo sunt atque pariatur. Ducimus quasi corrupti repudiandae aut, error accusantium necessitatibus culpa molestias in vero nostrum tempora inventore, odio, recusandae dolore! Tenetur dicta corrupti placeat voluptates modi delectus rem quo?</p>
    </div>
  )
}

export default Home
