import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'


const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/job-portal.png" />
      </Head>

      
      <h1>Hello Bangladesh</h1>
     
    </div>
  )
}

export default Home
