import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'
import Header from '../components/Headers'
import Layout from '../components/Layout'
import SideDrawer from '../components/SideDrawer'
import Hero from '../section/Hero'
import Link from 'next/link'
import Categories from '../section/Categories'

const Home: NextPage = () => {

  
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/job-portal.png" />
      </Head>
        <Hero />       
        <Categories />
    </div>
  )
}

export default Home
